#!/bin/bash
#fuzzer interactivo dentro de un programa 

ruta="ruta/a/carpeta"
cd $ruta
arch=$(find . -type f | fzf)

if [[ -n "$arch" ]]; then 
  echo "Seleccionaste: $arch"
else
  echo "No hay algo seleccionado"
fi
